application: greenyfy
version: 1
runtime: go
api_version: go1

handlers:
- url: /images
  static_dir: images

- url: /
  static_files: html/index.html
  upload: html/index\.html

- url: /.*
  script: _go_app